[package]
name = "boot-loader-entries"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
serde = { version = "1.0.216", features = ["derive"], optional = true }
thiserror = "2.0.4"

[features]
serde = ['dep:serde']
