[package]
name = "instant-netboot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
async-tftp = "0.3.6"
tokio = { version = "1.42.0", features = ["macros", "rt"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
